const nodemailer = require('nodemailer');
const { marked } = require('marked');

// Global transporter singleton for testing
let testTransporter = null;

async function getTransporter() {
  if (testTransporter) return testTransporter;
  
  try {
    // For local prototype, we create an Ethereal email account automatically
    const testAccount = await nodemailer.createTestAccount();
    
    testTransporter = nodemailer.createTransport({
      host: 'smtp.ethereal.email',
      port: 587,
      secure: false, // true for 465, false for other ports
      auth: {
        user: testAccount.user, // generated ethereal user
        pass: testAccount.pass, // generated ethereal password
      },
    });

    console.log(`[Email Service] Initialized Ethereal SMTP service.`);
    return testTransporter;
  } catch (error) {
    console.error(`[Email Service] Failed to initialize transporter: ${error.message}`);
    throw error;
  }
}

/**
 * Sends a stylized AI Generation report via email
 */
async function sendGenerationReport(toAddress, subject, markdownContent) {
  try {
    const transporter = await getTransporter();

    // Convert markdown into HTML
    const htmlBody = marked.parse(markdownContent);

    // Provide a wrapper template for the email
    const fullHtmlTemplate = `
      <div style="font-family: Arial, sans-serif; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
        <h2 style="color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px;">
          Manikanta Enterprises - AI Strategy Report
        </h2>
        <div style="margin-top: 20px; line-height: 1.6;">
          ${htmlBody}
        </div>
        <p style="margin-top: 40px; font-size: 12px; color: #888; text-align: center;">
          This is an automated report generated by the AI Customer Segment Analyzer.
        </p>
      </div>
    `;

    // Dispatch the email
    const info = await transporter.sendMail({
      from: '"Manikanta AI Analyzer" <noreply@manikanta.enterprises>', // sender address
      to: toAddress, // list of receivers
      subject: `AI Strategy: ${subject}`, // Subject line
      html: fullHtmlTemplate, // html body
    });

    console.log(`[Email Service] Message sent: ${info.messageId}`);
    
    // Preview only available when sending through an Ethereal account
    const previewUrl = nodemailer.getTestMessageUrl(info);
    console.log(`[Email Service] Preview URL: ${previewUrl}`);

    return {
      success: true,
      messageId: info.messageId,
      previewUrl
    };

  } catch (error) {
    console.error(`[Email Service] Failed to send email:`, error);
    return {
      success: false,
      error: error.message
    };
  }
}

module.exports = {
  sendGenerationReport
};
